# This is a basic workflow to help you get started with Actions

name: Build and publish gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Sphinx documentations
        run: |
          mkdir -p docs/MapMint ; 
          for i in $(ls MapMint) ; do 
            docker run --rm -v $(pwd)/MapMint/$i:/docs sphinxdoc/sphinx make html ; 
            sudo mv MapMint/$i/_build/html docs/MapMint/$i ;
            sudo cp _config.yml docs/MapMint/$i ;
          done
          mkdir -p docs/MapMint4ME ; 
          for i in $(ls MapMint4ME) ; do 
            docker run --rm -v $(pwd)/MapMint4ME/$i:/docs sphinxdoc/sphinx make html ; 
            sudo mv MapMint4ME/$i/_build/html docs/MapMint4ME/$i ; 
            sudo cp _config.yml docs/MapMint4ME/$i ;
          done
          sudo cp _config.yml docs/ ;
          sudo touch docs/.nojekyll
          
      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/
